### ISSUE TITLE
please update

### ISSUE THREAD

**Issue by FalangGG** [ebodziony/gladiatus-script#4]
AutoQuest doesn't work anymore. And it stuck your script if we let the auto quest activated.  So could you please check on it ??

**Comment by ebodziony** [comment]
#2 related issue

**Comment by kubailey112** [comment]
I would like to mention and I have tested, the quest part and sometimes the script will freeze up on Microsoft Edge. Running in Google Chrome there is no issues at all! Just thought I'd put that out there incase anyone has issues in the future.
