### ISSUE TITLE
Arenas not working

### ISSUE THREAD

**Issue by Lyucerna** [ebodziony/gladiatus-script#9]
For some time now the arenas just are not working. 
When pressing AUTO GO it goes to the arena screen, but then does not attack

**Comment by SebastianDeChiara** [comment]
It has something to do with line 960 in the script:

`const inCircusProvPage = document.getElementsByTagName("td")[3].firstChild.hasClass("awesome-tabs current");`

Console throws this error: Uncaught TypeError: document.getElementsByTagName(...)[3].firstChild.hasClass is not a function

**Comment by ebodziony** [comment]
@Lyucerna, @SebastianDeChiara I made a hotfix, it should work now.
